### ISSUE TITLE
FastSignal performance

### ISSUE THREAD

**Issue by sleepyyapril** [noahrepublic/DataKeep#16]
Just thought you might want to be aware
![image](https://github.com/noahrepublic/DataKeep/assets/123355664/84d99288-d88c-40fe-9b85-8c82a422c824)

**Comment by noahrepublic** [comment]
Will look into changing

Can I see the code you used to benchmark?

**Comment by sleepyyapril** [comment]
Sorry for super late response, benchmark was done by Aspecky (who made LemonSignal)

**Comment by lucasmz-dev** [comment]
This benchmark seems quite off. https://devforum.roblox.com/t/when-a-flexible-extensible-event-library/2996912/24?u=lucasmz_rbx

It would make sense in Deferred mode.

**Comment by lucasmz-dev** [comment]
![image](https://github.com/user-attachments/assets/d1c88e5c-7428-4354-acd6-e49ea0a1af54)
![image](https://github.com/user-attachments/assets/5ee8f0c1-9442-4f6e-bbf2-fe124a9a3681)
![image](https://github.com/user-attachments/assets/2fa8c8e6-6213-4d5d-919c-a5a95974114c)

(I have no idea what he meant here by connecting speed, both FastSignal and LemonSignal do the same here, GoodSignal uses a less complex function here so therefore wins)

LemonSignal does seem to be faster in certain cases for firing, though I haven't tested where there's multiple threads that need yielding. Otherwise it seems quite similar to FastSignal and seems to use the same "doubly-linked list" that was used originally in FastSignal to make `:Disconnect` faster. Both GoodSignal and FastSignal use the same `:Fire` code.

I haven't been in Roblox for a while, so I'm still readjusting and I probably have missed quite a few performance changes in Luau I could apply.

I did some updates, but 10.2.1 is fine and probably more stable, I'm still figuring this stuff out. Typing is complicated.

**Comment by noahrepublic** [comment]
Thank you for this follow-up. 


Would you recommend bumping to 10.2.1? Also, the addition of full types will be amazing.

**Comment by lucasmz-dev** [comment]
10.2.1 is what you're using, the newest is 10.3.1; I'm trying to get generic types working, it's a bit complicated because FastSignal separates Deferred and Immediate into two versions and then a third script decides which to use... I'm trying to figure out what kind of organization works better to maintain this kind of thing.

You may get typing issues with the update, so I don't know. Otherwise the code itself should be the same. Except it is no longer supported to call Signal.Deferred or Signal.Immediate cuz that just didn't work IIRC with typing, or broke it.

**Comment by lucasmz-dev** [comment]
Hey when you say full types do you mean generic types? I'm very much lost on Luau :sweat_smile:

**Comment by lucasmz-dev** [comment]
> though I haven't tested where there's multiple threads that need yielding

Correction here, because I forgot a comma, LemonSignal I believe runs better when there's code that yields. That's not the focus on FastSignal though.

**Comment by noahrepublic** [comment]
> 10.2.1 is what you're using, the newest is 10.3.1; I'm trying to get generic types working, it's a bit complicated because FastSignal separates Deferred and Immediate into two versions and then a third script decides which to use... I'm trying to figure out what kind of organization works better to maintain this kind of thing.
> 
> 
> 
> You may get typing issues with the update, so I don't know. Otherwise the code itself should be the same. Except it is no longer supported to call Signal.Deferred or Signal.Immediate cuz that just didn't work IIRC with typing, or broke it.

Awesome. Keep me updated when generics are done and will be sure to update. Aside from that seems this is resolved

**Comment by lucasmz-dev** [comment]
I think they should be working just fine now? Let me know if you encounter any issues, 10.3.2 was just released, almost no changes from 10.3.1 though;
It's quite hard to do anything with Roblox Studio on Linux unfortunately, sorry about the delay 😵‍💫 I finally got my PC working again so :D

**Comment by noahrepublic** [comment]
Thank you! We already bumped the version in type rewrite
