### ISSUE TITLE
Function 'Plugins'

### ISSUE THREAD

**Issue by noahrepublic** [noahrepublic/DataKeep#2]
If someone wanted some specific kind of compression they could get a plugin that takes cache data and compresses all of U types

Would attach pre-save

You specify an order via function chaining, and it'll generate a "processor" instance for you
and you can attach that processor instance to different things

You could have something that would strip a subset of data for example
and then a compression plugin after that
multipurpose data cache

**Comment by golden2402** [comment]
good references for this:
- https://postcss.org/
- https://unifiedjs.com/

**Comment by noahrepublic** [comment]
I was thinking of just allowing a function to be attached to a value "pre-save" or something called on each loop of the data table and the user can use if statements to decide if they want to compress or whatever.

This seems weird. Do you have any other ideas?

**Comment by golden2402** [comment]
I think that pattern is fine. I’m not entirely sure what you mean by “each loop” of the data table.

I’d think the only argument sent as input to any of the processors is the current state of the data table—they choose what they want to do with it and return a new data state (or choose not to!).

**Comment by noahrepublic** [comment]
I could pass the newest data like how :UpdateAsync() works. And the developer can do whatever they decide or, don't have to define a pre-save.

Say they only wanted one data key to be compressed, they can loop and find that key. Unsure if they should be able to define per-keep or per-store

**Comment by golden2402** [comment]
That’s good. I think it's safe to assume that the user should have a good understanding of the data they're working with; they shouldn't have to loop, just find the exact key they want.

I think a critical design point you should focus on is giving people the ability to create unique data transformations in a familiar package (which is why I suggest functions).

Since the plugins would only be concerned with operating on the data that is passed to them, this also means that users could embed plugins inside their own processing functions—to compress a specific subset of data, for example.

Something to consider would be depth: how do you want to specify how deep a plugin should go? Should you create separate plugins for shallow and recursive compression?

**Comment by noahrepublic** [comment]
Trying to decide how to uncompress the data on load. sounds like a pain for the user

**Comment by noahrepublic** [comment]
Should Presave just be a function? Or class that allows :RegisterProcessor and they get chained after one another

**Comment by JakeyWasTaken** [comment]
I think the update async idea where the data is passed in then returned out (maybe mutated maybe not) is a good idea, couldnt you just have a set of functions like:

```
:PreSave(function(Data)
     -- Mutate
     return Data
end)

:PreLoad(function(Data)
      -- Mutate
     return Data
end)
```

Imo this would allow for the most functionality

I might have misunderstood something in the message chain though

**Comment by noahrepublic** [comment]
I like this idea. Provides lots of customization, with a familiar API. And doesn't lose the function of chaining.

How does this look?

```
store:AttachToSave(function(rawData)
      -- compress
      return rawData
end, function(compressed)
      -- decompress
      return compressed
end)

```

This helps minimize small mistakes like not defining a decompression function to avoid data loss/corruptions

**Comment by noahrepublic** [comment]
Settled on :PreSave & :PreLoad
